### ISSUE TITLE
Histocat not downloading on MacOS Big Sur

### ISSUE THREAD

**Issue by Bunmi0616** [BodenmillerGroup/histoCAT#117] opened 2022-08-30 20:43 UTC
Hello, I am trying to use the program on a computer with BigSur and I keep getting an error report. Do you have any updates/work arounds?

Kind regards,
Bunmi

**Comment by DenisSch** [comment] 2022-12-06 17:07
Duplicate of #73

**Closed by DenisSch** 2022-12-06 17:07 UTC
